---
title: "R Notebook"
---

```{r}
library(mice)
library(miceadds)
library(tidyverse)
```

```{r}
load("implist.RData")
```

```{r}
expo <- function(fit_pool){
  coef <- round(fit_pool$estimate, digits = 2)
  CI <- paste(round(fit_pool$`2.5 %`, digits = 2), round(fit_pool$`97.5 %`, digits = 2), sep=" , ")
  CI <- paste("(", CI, ")", sep = "")
  coef <- paste(coef, CI, sep=" ")
  
  expo <- data.frame(var = fit_pool$term, b=coef)
  write.csv(expo, file=paste0("D:/eq5d/output/", deparse(substitute(fit_pool)), ".csv"))
  return(expo)
}

```



```{r}
fit <- with(implist, exp = lm(eq5d_index ~ age5 + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

age_cat <- summary(pool(fit), conf.int = T)

expo(age_cat)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

# change to linear age

```{r}
fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

age_linear <- summary(pool(fit), conf.int = T)

expo(age_linear)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

# spline

```{r}
for (i in 1:20) {
  implist[[i]]$dif70 <- implist[[i]]$CurrAge_cent-1
  implist[[i]]$over70 <- ifelse(implist[[i]]$CurrAge_cent>=1, 1, 0)
  implist[[i]]$xdif70 <- implist[[i]]$dif70*implist[[i]]$over70
}
```

```{r}
fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + xdif70 + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

age_spl1 <- summary(pool(fit), conf.int = T)

expo(age_spl1)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

```{r}
# the same as above
library(lspline)

fit <- with(implist, exp = lm(eq5d_index ~ lspline(CurrAge_cent, 1, marginal = F) + male + ethn + imd + bmi_cat + smk + trtbp +mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

fit_pool <- summary(pool(fit), conf.int = T)
fit_pool[, c(1, 2, 6)]

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

```{r}

fit <- with(implist, exp = lm(eq5d_index ~ lspline(CurrAge_cent, c(-0.5, 1), marginal = T) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

fit_pool <- summary(pool(fit), conf.int = T)
fit_pool[, c(1, 2, 6)]

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2

```

```{r}

fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5)) + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

age_spl2 <- summary(pool(fit), conf.int = T)

expo(age_spl2)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

# interaction


```{r}
# linear age

fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + male + ethn + imd + bmi_cat + smk + trtbp + CurrAge_cent*mental + CurrAge_cent*cancer + CurrAge_cent*dm_0_10_plus + CurrAge_cent*cvd_hist + CurrAge_cent*crv_1_plus + CurrAge_cent*mi_0_1 + CurrAge_cent*stroke_0_1 + CurrAge_cent*crv_0_1))

age_linear_int <- summary(pool(fit), conf.int = T)

expo(age_linear_int)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```


```{r}
# spline with 1 knots

fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + 
  CurrAge_cent*mental + CurrAge_cent*cancer + CurrAge_cent*dm_0_10_plus + CurrAge_cent*cvd_hist + CurrAge_cent*crv_1_plus + CurrAge_cent*mi_0_1 + CurrAge_cent*stroke_0_1 + CurrAge_cent*crv_0_1 +
   I((CurrAge_cent-1)*(CurrAge_cent>=1))*mental + I((CurrAge_cent-1)*(CurrAge_cent>=1))*cancer + I((CurrAge_cent-1)*(CurrAge_cent>=1))*dm_0_10_plus + I((CurrAge_cent-1)*(CurrAge_cent>=1))*cvd_hist + I((CurrAge_cent-1)*(CurrAge_cent>=1))*crv_1_plus + I((CurrAge_cent-1)*(CurrAge_cent>=1))*mi_0_1 + I((CurrAge_cent-1)*(CurrAge_cent>=1))*stroke_0_1 + I((CurrAge_cent-1)*(CurrAge_cent>=1))*crv_0_1))

age_spl1_int <- summary(pool(fit), conf.int = T)

expo(age_spl1_int)

age_spl1_int[, c(1, 2, 6)]

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

```{r}
# spline with 1 knots, only keep significant interactions in above model

for (i in 1:20) {
  implist[[i]]$mi_only <- ifelse(implist[[i]]$cvd_hist=="MI 1yr+ only", 1, 0)
  implist[[i]]$angina_only <- ifelse(implist[[i]]$cvd_hist=="Angina ever only", 1, 0)
  implist[[i]]$stroke_only <- ifelse(implist[[i]]$cvd_hist=="stroke 1yr+ only", 1, 0)
  implist[[i]]$two_more <- ifelse(implist[[i]]$cvd_hist=="Two or more", 1, 0)
}


fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + angina_only + mi_only + stroke_only + two_more + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1 +
  CurrAge_cent*angina_only + 
    I((CurrAge_cent-1)*(CurrAge_cent>=1))*mi_only))

age_spl1_int_re <- summary(pool(fit), conf.int = T)

expo(age_spl1_int_re)

age_spl1_int_re[, c(1, 2, 6)]

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2


```




```{r}
# spline with 2 knots

fit <- with(implist, exp = lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5)) + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + CurrAge_cent*mental + CurrAge_cent*cancer + CurrAge_cent*dm_0_10_plus + CurrAge_cent*cvd_hist + CurrAge_cent*crv_1_plus + CurrAge_cent*mi_0_1 + CurrAge_cent*stroke_0_1 + CurrAge_cent*crv_0_1 +  
 I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*mental + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*cancer + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*dm_0_10_plus + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*cvd_hist + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*crv_1_plus + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*mi_0_1 + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*stroke_0_1 + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5))*crv_0_1 + 
 I((CurrAge_cent-1)*(CurrAge_cent>=1))*mental + I((CurrAge_cent-1)*(CurrAge_cent>=1))*cancer + I((CurrAge_cent-1)*(CurrAge_cent>=1))*dm_0_10_plus + I((CurrAge_cent-1)*(CurrAge_cent>=1))*cvd_hist + I((CurrAge_cent-1)*(CurrAge_cent>=1))*crv_1_plus + I((CurrAge_cent-1)*(CurrAge_cent>=1))*mi_0_1 + I((CurrAge_cent-1)*(CurrAge_cent>=1))*stroke_0_1 + I((CurrAge_cent-1)*(CurrAge_cent>=1))*crv_0_1                  
))

age_spl2_int <- summary(pool(fit), conf.int = T)

expo(age_spl2_int)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```


# plot

```{r}
# use average eq5d index for each age year as the observed dot
# use spline 1 knot
library(gmodels) # calculate confidence interval
library(ggplot2)


data <- implist[[1]][order(implist[[1]]$CurrAge_cent), ]

fit <- lm(eq5d_index ~ CurrAge_cent + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + cvd_hist + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1, data=data)

# new predict data

dt <- data.frame(CurrAge_cent=seq(-3, 4.2, by=0.1), age = 30:102,
                 male=0, ethn="White", imd=3, bmi_cat="18.5-25", smk="non-smoker", trtbp=0, mental=0, cancer=0, dm_0_10_plus="no diabetes", cvd_hist="None", crv_1_plus=0, mi_0_1=0, stroke_0_1=0, crv_0_1=0)

dt$ethn <- as.factor(dt$ethn)
dt$imd <- as.factor(dt$imd)
dt$bmi_cat <- as.factor(dt$bmi_cat)
dt$smk <- as.factor(dt$smk)
dt$trtbp <- as.factor(dt$trtbp)
dt$mental <- as.factor(dt$mental)
dt$cancer <- as.factor(dt$cancer)
dt$dm_0_10_plus <- as.factor(dt$dm_0_10_plus)
dt$cvd_hist <- as.factor(dt$cvd_hist)
dt$crv_1_plus <- as.factor(dt$crv_1_plus)
dt$mi_0_1 <- as.factor(dt$mi_0_1)
dt$stroke_0_1 <- as.factor(dt$stroke_0_1)
dt$crv_0_1 <- as.factor(dt$crv_0_1)

pred <- predict(fit, newdata = dt)




agem <- data %>% 
  group_by(age) %>% 
  summarise(EQ5D=ci(eq5d_index)[1], 
            lowCI=ci(eq5d_index)[2],
            hiCI=ci(eq5d_index)[3]) 
  

agem <- as.data.frame(agem)

ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=dt, aes(x=age, y=pred))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))


```
the graph above is not right. because the observed dots are general population, the red prediction line is based on assumptions of covariates except age


```{r}
# linear

fit <- lm(eq5d_index ~ CurrAge_cent, data = data)

# agem <- data %>% 
#   group_by(age) %>% 
#   summarise(EQ5D=ci(eq5d_index)[1], 
#             lowCI=ci(eq5d_index)[2],
#             hiCI=ci(eq5d_index)[3]) 
#   
# 
# agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=data, aes(x=age, y=predict(fit)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/linear.png")
```




```{r}
# use average eq5d index for each age year as the observed dot
# use spline 1 knot

fit <- lm(eq5d_index ~ CurrAge_cent + xdif70, data=data)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=data, aes(x=age, y=predict(fit)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/spl_1.png")
```



```{r}
# spline, 2 knots
fit <- lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent+0.5)*(CurrAge_cent>=-0.5)) + I((CurrAge_cent-1)*(CurrAge_cent>=1)), data=data)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=data, aes(x=age, y=predict(fit)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/spl_2.png")
```



```{r}
# 5 year interval

fit <- lm(eq5d_index ~ age5, data = data)

# agem <- data %>% 
#   group_by(age) %>% 
#   summarise(EQ5D=ci(eq5d_index)[1], 
#             lowCI=ci(eq5d_index)[2],
#             hiCI=ci(eq5d_index)[3]) 
#   
# 
# agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=data, aes(x=age, y=predict(fit)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/5_y_intv.png")
```


#### on angina/MI history 

```{r}
# angina
# use spline 1 knot

data <- implist[[1]][order(implist[[1]]$CurrAge_cent), ]

dt_ang <- subset(data, cvd_hist=="Angina ever only")
dt_mi <- subset(data, cvd_hist=="MI 1yr+ only")
dt_none <- subset(data, cvd_hist=="None")

fit <- lm(eq5d_index ~ CurrAge_cent + xdif70 + angina_only + mi_only + stroke_only + two_more, data=data)
```


```{r}
# likelihood ratio test

fit0 <- lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + angina_only + mi_only + stroke_only + two_more + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1, data=data)


fit1 <- lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + angina_only + mi_only + stroke_only + two_more + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1 +
  CurrAge_cent*angina_only + 
    I((CurrAge_cent-1)*(CurrAge_cent>=1))*mi_only, data=data)

anova(fit0, fit1) # F test
anova(fit0, fit1, test="LRT") # chi-square test
```

```{r}
library(lmtest)
lrtest(fit0, fit1)

```


```{r}
# angina people
agem <- dt_ang %>% 
  group_by(age) %>% 
  summarise(EQ5D=ci(eq5d_index)[1], 
            lowCI=ci(eq5d_index)[2],
            hiCI=ci(eq5d_index)[3]) 

agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=dt_ang, aes(x=age, y=predict(fit, dt_ang)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/ang.png")
x
```

```{r}
# mi people
agem <- dt_mi %>% 
  group_by(age) %>% 
  summarise(EQ5D=ci(eq5d_index)[1], 
            lowCI=ci(eq5d_index)[2],
            hiCI=ci(eq5d_index)[3]) 

agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=dt_mi, aes(x=age, y=predict(fit, dt_mi)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/mi.png")
x
```


```{r}
# none cv history people
agem <- dt_none %>% 
  group_by(age) %>% 
  summarise(EQ5D=ci(eq5d_index)[1], 
            lowCI=ci(eq5d_index)[2],
            hiCI=ci(eq5d_index)[3]) 

agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=dt_none, aes(x=age, y=predict(fit, dt_none)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/none.png")
x
```

# after add interaction

```{r}
fit <- lm(eq5d_index ~ CurrAge_cent*angina_only + xdif70*mi_only + stroke_only + two_more, data=data)
```


```{r}
# angina people
agem <- dt_ang %>% 
  group_by(age) %>% 
  summarise(EQ5D=ci(eq5d_index)[1], 
            lowCI=ci(eq5d_index)[2],
            hiCI=ci(eq5d_index)[3]) 

agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=dt_ang, aes(x=age, y=predict(fit, dt_ang)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/ang_int.png")
x
```


```{r}
# mi people
agem <- dt_mi %>% 
  group_by(age) %>% 
  summarise(EQ5D=ci(eq5d_index)[1], 
            lowCI=ci(eq5d_index)[2],
            hiCI=ci(eq5d_index)[3]) 

agem <- as.data.frame(agem)

x <- ggplot(agem, aes(x=age, y=EQ5D)) +
  geom_point(size = 1)+
  geom_errorbar(aes(ymax=hiCI, ymin=lowCI))+
  geom_line(color='red', data=dt_mi, aes(x=age, y=predict(fit, dt_mi)))+
  theme(panel.background = element_blank())+
  scale_x_continuous(breaks = seq(30, 105, by=5))+
  scale_y_continuous(limits = c(-0.5,1))

ggsave(x, filename = "D:/eq5d/output/mi_int.png")
x
```

# base HSE 2011 only

```{r}
implist2011 <- implist

for (i in 1:20) {
  implist2011[[i]] <- subset(implist[[i]], year==2011)
}
```


```{r}
# no interaction
fit <- with(implist2011, exp = lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + angina_only + mi_only + stroke_only + two_more + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1))

fit2011 <- summary(pool(fit), conf.int = T)

fit2011[, c(1, 2, 6)]

expo(fit2011)

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2
```

```{r}
# add interaction
fit <- with(implist2011, exp = lm(eq5d_index ~ CurrAge_cent + I((CurrAge_cent-1)*(CurrAge_cent>=1)) + male + ethn + imd + bmi_cat + smk + trtbp + mental + cancer + dm_0_10_plus + angina_only + mi_only + stroke_only + two_more + crv_1_plus + mi_0_1 + stroke_0_1 + crv_0_1 +
  CurrAge_cent*angina_only + 
    I((CurrAge_cent-1)*(CurrAge_cent>=1))*mi_only))

fit2011_int <- summary(pool(fit), conf.int = T)

fit2011_int[, c(1, 2, 6)]

R2 <- mean(sapply(1:length(fit), function(x) summary(fit[[x]])$r.squared))
R2

```



